### ISSUE TITLE
HEy author pls edit your post !

### ISSUE THREAD

**Issue by jinoh808** [juliansprt/OpenCvSharpDNN#1]
you forgot to upload below folder 
"OpenCvSharpDNN\OpenCVCSharpDNN\OpenCVCSharp.Example\bin\Debug\data"
and you forgot to upload "coco.names" file and "friends.jpg" file 

pls edit your post

**Comment by juliansprt** [comment]
Hi,
In this link: https://drive.google.com/drive/folders/1oj9p04mPjbbCbq1qSK8ChMjOhMLMpk42?usp=sharing
You can download pre-trained models and label's files
