### ISSUE TITLE
where is your yolov3-wider_16000.weights?

### ISSUE THREAD

**Issue by zhangyufei1995** [juliansprt/OpenCvSharpDNN#3]
as the title

**Comment by juliansprt** [comment]
Duplicate of #1 

You can download all data files in this link:
https://drive.google.com/drive/folders/1oj9p04mPjbbCbq1qSK8ChMjOhMLMpk42?usp=sharing

**Comment by fatalfeel** [comment]
2 sites can download
https://github.com/sthanhng/yoloface/tree/master

https://huggingface.co/spaces/simayhosmeyve/Image_Enhancement/blob/92d7f4409bf83af30fb5a619a7db5be2958c7a88/yolov3-wider_16000.weights
