### ISSUE TITLE
All male

### ISSUE THREAD

**Issue by eluancardoso** [juliansprt/OpenCvSharpDNN#4]
i tried every female photo but return male 99%

**Comment by juliansprt** [comment]
El modelo fue realizado por este repositorio: https://github.com/GilLevi/AgeGenderDeepLearning
Para mejorar la precisión, alinee la imagen con respecto a la posición de la cara. Algo similar a esto: https://medium.com/@dsfellow/precise-face-alignment-with-opencv-dlib-e6c8acead262

**Comment by juliansprt** [comment]
ok
